
package view;

import control.Controller;
import java.util.ArrayList;
import model.Flight;

/**
 *
 * @author hadi
 */
public class Flightdetails extends javax.swing.JFrame {

    /**
     * Creates new form EditProfessor
     */
    public Flightdetails() {
        initComponents();
         fillCombo();
    }
    
    private void fillCombo(){
        combo.removeAllItems();
        
        ArrayList<String> ALLCITY = new Controller().getallcity();
        
        for(int i=0; i<ALLCITY.size();i++){
            combo.addItem(ALLCITY.get(i)+"");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        departure = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        arrival = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        Info = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        pssn = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Flights from a specific city");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(148, 20, 276, 29);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Flight Number");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(38, 154, 149, 29);

        num.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(num);
        num.setBounds(249, 157, 131, 28);

        departure.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(departure);
        departure.setBounds(249, 222, 131, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Departure city");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(38, 219, 151, 29);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel4.setText("Arrival City");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(38, 284, 151, 29);

        arrival.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(arrival);
        arrival.setBounds(249, 287, 131, 28);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setText("City");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(38, 82, 39, 29);

        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboActionPerformed(evt);
            }
        });
        getContentPane().add(combo);
        combo.setBounds(249, 82, 130, 22);

        Info.setText("Get Info");
        Info.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoActionPerformed(evt);
            }
        });
        getContentPane().add(Info);
        Info.setBounds(440, 82, 72, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel5.setText("PSSN");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(38, 353, 151, 40);

        pssn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pssnActionPerformed(evt);
            }
        });
        getContentPane().add(pssn);
        pssn.setBounds(249, 367, 131, 22);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\HP\\OneDrive\\Pictures\\sky.PNG")); // NOI18N
        jLabel7.setText("jLabel7");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 570, 470);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void InfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoActionPerformed
        
    
        String city = (String) combo.getSelectedItem();
        Flight flight=new Controller().getflightBycity(city);
        
        if(flight!=null){
            num.setText(flight.getFlightnumber());
            departure.setText(flight.getFrom());
            arrival.setText(flight.getTo());
            pssn.setText(String.valueOf(flight.getpssn()));
            
        }
        
    }//GEN-LAST:event_InfoActionPerformed

    private void comboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboActionPerformed

    private void pssnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pssnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pssnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Flightdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Flightdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Flightdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Flightdetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Flightdetails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Info;
    private javax.swing.JTextField arrival;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JTextField departure;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField num;
    private javax.swing.JTextField pssn;
    // End of variables declaration//GEN-END:variables
}
